### ISSUE TITLE
Citations are `(` instead of `[`. 

### ISSUE THREAD

**Issue by rowanc1** [ncssm/morgantonscientific2024#16]
The citations in a lot of places are in brackets, but these need to be `[@citekey]`.

**Comment by taylorgibson** [comment]
I'll take a look today. To clarify, are they currently using parenthesis `(@citekey)`, and they need to use brackets `[@citekey]`. Is that correct?

Should I make these changes in a separate branch, one branch per article, to review before merging into main?

**Comment by rowanc1** [comment]
Yes, that is correct. Feel free to change all at once!

In the preview it will change from looking like (Cockett (2024)) to (Cockett, 2024).

**Comment by taylorgibson** [comment]
Should be fixed by #18
