### ISSUE TITLE
Move editors note to different folder

### ISSUE THREAD

**Issue by rowanc1** [ncssm/morgantonscientific2024#20]
Currently the actions are expecting that all papers have a myst.yml, and are failing at the moment. This is something we should make less strict, but at the moment, I think we should move the editors note out of the papers folder into a different main directory, maybe `journal`?

We will also fix up the action, so this doesn't fail in the future:
![image](https://github.com/user-attachments/assets/d33c40dd-1644-4e77-aed5-fa8573a336c2)

**Comment by taylorgibson** [comment]
@rowanc1  Does this require action on my part?
