### ISSUE TITLE
Spacing issue on website

### ISSUE THREAD

**Issue by taylorgibson** [ncssm/morgantonscientific2024#34]
On [this article](https://morgantonscientific.ncssm.edu/articles/01904a8d-ffdd-777a-97a7-a4be7e5747c3), there's a random space that isn't in the `article.md` file in the `jonnavithula` article.

<img width="861" alt="image" src="https://github.com/user-attachments/assets/bb191038-b730-4f13-a9a0-d8076c05f438">

Is this a bug?

**Comment by rowanc1** [comment]
![image](https://github.com/user-attachments/assets/4133e29b-6981-4ff4-a4cd-4c8eb74471cb)
