### ISSUE TITLE
Table formatting in kulla-tang paper

### ISSUE THREAD

**Issue by taylorgibson** [ncssm/morgantonscientific2024#45]
The table in the PDF version of the kulla-tang paper is not formatting corectly.

![image](https://github.com/user-attachments/assets/265c6d1b-985d-43ef-93fe-d34230e4d2e0)

**Comment by rowanc1** [comment]
![image](https://github.com/user-attachments/assets/3e0e9314-f0cb-429f-a902-ef3a5df909a4)

![image](https://github.com/user-attachments/assets/e2001193-820e-44f9-9c22-4cc44e83e11a)

**Comment by fwkoch** [comment]
Addressed here: https://github.com/ncssm/morgantonscientific2024/pull/48!
