### ISSUE TITLE
Extraneous code outputs on srinath paper

### ISSUE THREAD

**Issue by taylorgibson** [ncssm/morgantonscientific2024#46]
The PDF version of the srinath paper has a lot of code outputs that do not appear relevant and are not in the version on the website. For example, the output below:
![image](https://github.com/user-attachments/assets/e65a7a90-a767-482d-b95f-3390d1582924)

**Comment by fwkoch** [comment]
This ended up being a tiny change in the `myst.yml`: https://github.com/ncssm/morgantonscientific2024/pull/49/files#diff-b10e44d9df9e53b6831ad2ea26568c6c92b5aa270b386d708445644055b42e9eR42-R43 - fixed now!
